# Generated by Django 3.2.4 on 2022-07-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0002_alter_orderfooditem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(through='foodDelivery.OrderFoodItem', to='foodDelivery.FoodItem'),
        ),
    ]
